version: "3.7"

services:
  fastapi:
    build: ./app/
    container_name: chall-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - internal
    environment:
      - PROJECT_NAME='Valhala'
      - APP_ENV=local
      - SECRET_KEY=secret
      - DEBUG=False
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5000
      - UVICORN_RELOAD=True
      - UVICORN_ACCESS_LOG=False
      - ALLOWED_HOSTS='*'
  bot:
    build: ./bot/
    container_name: chall-bot
    init: true
    environment:
      - CHALLENGE_HOST=0.0.0.0
      - CHALLENGE_COOKIE=IngeHack{y0u_4r3_4_tru3_cr0ss_pr0t0_s1te_v1k1ng}
    depends_on:
      - redis
    networks:
      - internal
  redis:
    image: redis:6.0-alpine
    container_name: redis
    restart: always
    command: redis-server --loglevel verbose
    networks:
      - internal

networks:
  internal: